#!/bin/sh
# made using https://github.com/JulianoGianlupi/cc3d-nanoHub-tool-setuper
/usr/bin/invoke_app "$@" -C @tool/bin/test10.sh -t test10 \
                         -u compucell3d-4.4.0 \
                         -w captive \
                         -r none
